### ISSUE TITLE
训练代码报错

### ISSUE THREAD

**Issue by zhaojianhui-zjh** [destwang/DCN#10]
Traceback (most recent call last):
  File "train_DCN.py", line 511, in <module>
    main()
  File "train_DCN.py", line 228, in main
    model = DCNForMaskedLM.from_pretrained(
  File "/home/zhaojianhui/DCN-main/transformers/modeling_utils.py", line 671, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/zhaojianhui/DCN-main/transformers/modeling_dcn.py", line 1124, in __init__
    self.cls = BertOnlyMLMHead(config)
  File "/home/zhaojianhui/DCN-main/transformers/modeling_dcn.py", line 586, in __init__
    self.predictions = BertLMPredictionHead(config)
  File "/home/zhaojianhui/DCN-main/transformers/modeling_dcn.py", line 543, in __init__
    self.pinyin_embeddings = nn.Embedding(config.pinyin_vocab_size,
AttributeError: 'BertConfig' object has no attribute 'pinyin_vocab_size'

**Comment by destwang** [comment]
你好，config文件应该使用chinese_roberta_wwm_ext_pytorch目录中提供的
